---
- name: Install nginx web server
  apt: name=nginx state=installed

- name: Copy nginx configuration for debmirror
  template: src=debmirror.conf.j2 dest=/etc/nginx/conf.d/debmirror.conf
  notify:
    - restart nginx
